services:
  - type: web
    name: altf-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AWS_REGION
        value: ap-northeast-2
      - key: S3_BUCKET_NAME
        value: altf-web-data-prod
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
